<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../SupplierPriceListFile.wsdl"/>
      <rootElement name="SupplierPrice" namespace="http://TargetNamespace.com/SupplierPriceListFile"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../SupplierPriceListInsert.wsdl"/>
      <rootElement name="XxwfsWfsukSupPrclstStgTblCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SupplierPriceListInsert"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [WED JUL 02 13:47:11 IST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:imp1="http://TargetNamespace.com/SupplierPriceListFile"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SupplierPriceListInsert"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/UKLubes-SOA/UKLubesSupplierPriceList/SupplierPriceListInsert"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/UKLubes-SOA/UKLubesSupplierPriceList/SupplierPriceListFile"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl pc imp1 plt wsdl jca xsd tns top ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <top:XxwfsWfsukSupPrclstStgTblCollection>
      <xsl:for-each select="/imp1:SupplierPrice/imp1:SupplierPriceType">
        <top:XxwfsWfsukSupPrclstStgTbl>
          <top:supplierName>
            <xsl:value-of select="imp1:SupplierName"/>
          </top:supplierName>
          <top:suppSiteName>
            <xsl:value-of select="imp1:SupplierSale"/>
          </top:suppSiteName>
          <top:suppSkuItem>
            <xsl:value-of select="imp1:SupplierSKU"/>
          </top:suppSkuItem>
          <top:suppPricingLitre>
            <xsl:value-of select="imp1:Price_Litre"/>
          </top:suppPricingLitre>
          <top:status>
            <xsl:text disable-output-escaping="no">NEW</xsl:text>
          </top:status>
        </top:XxwfsWfsukSupPrclstStgTbl>
      </xsl:for-each>
    </top:XxwfsWfsukSupPrclstStgTblCollection>
  </xsl:template>
</xsl:stylesheet>
