<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../CustomerPriceListFile.wsdl"/>
      <rootElement name="Customer" namespace="http://TargetNamespace.com/CustomerPriceListFile"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../PriceListInsert.wsdl"/>
      <rootElement name="XxwfsWfsukPrclistUploadTblCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PriceListInsert"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [TUE JUL 15 14:28:01 IST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/UKLubes-SOA/UKLubesPriceListing/PriceListInsert"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/UKLubes-SOA/UKLubesPriceListing/CustomerPriceListFile"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:imp1="http://TargetNamespace.com/CustomerPriceListFile"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PriceListInsert"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns pc plt wsdl imp1 jca xsd ns0 top xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <top:XxwfsWfsukPrclistUploadTblCollection>
      <xsl:for-each select="/imp1:Customer/imp1:CustomerType">
        <xsl:if test="string-length(normalize-space(imp1:PriceListName)) != 0.0">
          <top:XxwfsWfsukPrclistUploadTbl>
            <top:priceListName>
              <xsl:value-of select="imp1:PriceListName"/>
            </top:priceListName>
            <top:oracleItem>
              <xsl:value-of select="imp1:OracleItem"/>
            </top:oracleItem>
            <top:uom>
              <xsl:value-of select="imp1:UOM"/>
            </top:uom>
            <top:unitSellingPrice>
              <xsl:value-of select="imp1:UnitSellingPrice"/>
            </top:unitSellingPrice>
            <top:startDate>
              <xsl:value-of select="oraext:query-database(concat(&quot;select to_char(to_date('&quot;,imp1:StartDate,&quot;','DD-MON-YY'),'YYYY-MM-DD')StartDate from dual&quot;),false(),false(),&quot;jdbc/APPSnonXA&quot;)"/>
            </top:startDate>
            <top:endDate>
              <xsl:value-of select="oraext:query-database(concat(&quot;select to_char(to_date('&quot;,imp1:EndDate,&quot;','DD-MON-YY'),'YYYY-MM-DD')EndDate from dual&quot;),false(),false(),&quot;jdbc/APPSnonXA&quot;)"/>
            </top:endDate>
            <top:processFlag>
              <xsl:text disable-output-escaping="no">NEW</xsl:text>
            </top:processFlag>
            <top:creationDate>
              <xsl:value-of select="xp20:current-date()"/>
            </top:creationDate>
            <top:lastUpdateDate>
              <xsl:value-of select="xp20:current-date()"/>
            </top:lastUpdateDate>
          </top:XxwfsWfsukPrclistUploadTbl>
        </xsl:if>
      </xsl:for-each>
    </top:XxwfsWfsukPrclistUploadTblCollection>
  </xsl:template>
</xsl:stylesheet>
