<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../FTP_GET_IN_COSTINTERFACE.wsdl"/>
      <rootElement name="Cost" namespace="http://TargetNamespace.com/FTP_GET_IN_COSTINTERFACE"/>
    </source>
    <source type="XSD">
      <schema location="../xsd/XSD_FileName.xsd"/>
      <rootElement name="FileName" namespace="http://www.filename.org"/>
      <param name="FN" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../DB_INS_OUT_ITM_CST_TBL.wsdl"/>
      <rootElement name="XxwfsWfsukItmCstStgCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_INS_OUT_ITM_CST_TBL"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [FRI JUL 11 16:35:47 IST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_INS_OUT_ITM_CST_TBL"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:fn="http://www.filename.org"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:imp1="http://TargetNamespace.com/FTP_GET_IN_COSTINTERFACE"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/UKLubes-SOA/UKLubesCostInterface/FTP_GET_IN_COSTINTERFACE"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/UKLubes-SOA/UKLubesCostInterface/DB_INS_OUT_ITM_CST_TBL"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl pc fn plt wsdl imp1 tns jca xsd top ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:param name="FN"/>
  <xsl:template match="/">
    <top:XxwfsWfsukItmCstStgCollection>
      <xsl:for-each select="/imp1:Cost/imp1:CostType">
        <top:XxwfsWfsukItmCstStg>
          <top:itemName>
            <xsl:value-of select="imp1:Item"/>
          </top:itemName>
          <top:description>
            <xsl:value-of select="imp1:Description"/>
          </top:description>
          <top:organizationName>
            <xsl:value-of select="imp1:Organization"/>
          </top:organizationName>
          <top:costType>
            <xsl:value-of select="imp1:CostType"/>
          </top:costType>
          <top:costElement>
            <xsl:value-of select="imp1:CostElement"/>
          </top:costElement>
          <top:subElement>
            <xsl:value-of select="imp1:SubElement"/>
          </top:subElement>
          <top:rateOrAmount>
            <xsl:value-of select="imp1:UnitCost"/>
          </top:rateOrAmount>
          <top:processStatus>
            <xsl:text disable-output-escaping="no">NEW</xsl:text>
          </top:processStatus>
          <top:creationDate>
            <xsl:value-of select="xp20:current-date()"/>
          </top:creationDate>
          <top:createdBy>
            <xsl:text disable-output-escaping="no">-1</xsl:text>
          </top:createdBy>
          <top:soaFile>
            <xsl:value-of select='concat($FN/fn:FileName/fn:FileName,"_",xp20:current-date())'/>
          </top:soaFile>
        </top:XxwfsWfsukItmCstStg>
      </xsl:for-each>
    </top:XxwfsWfsukItmCstStgCollection>
  </xsl:template>
</xsl:stylesheet>
