<?binding.jca SupplierPriceListInsert_db.jca?>
<wsdl:definitions name="SupplierPriceListInsert" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/UKLubes-SOA/UKLubesSupplierPriceList/SupplierPriceListInsert" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/UKLubes-SOA/UKLubesSupplierPriceList/SupplierPriceListInsert" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SupplierPriceListInsert">
    <plt:partnerLinkType name="SupplierPriceListInsert_plt">
        <plt:role name="SupplierPriceListInsert_role">
            <plt:portType name="tns:SupplierPriceListInsert_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SupplierPriceListInsert" schemaLocation="xsd/SupplierPriceListInsert_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="XxwfsWfsukSupPrclstStgTblCollection_msg">
        <wsdl:part name="XxwfsWfsukSupPrclstStgTblCollection" element="top:XxwfsWfsukSupPrclstStgTblCollection"/>
    </wsdl:message>
    <wsdl:portType name="SupplierPriceListInsert_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:XxwfsWfsukSupPrclstStgTblCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
